import Head from "next/head";
import styled from "styled-components";

import { Section, Container, Row } from '@/components/container';
import useColorTheme from "@/hooks/useColorTheme";


export default function Home() {
  const colors = useColorTheme();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Section id="background">
          <Container>
            <Row>

            </Row>
          </Container>
        </Section>
        <Section id="skills">
          <Container>

          </Container>
        </Section>
        <Section id="background">
          <Container>

          </Container>
        </Section>
      </Layout>
    </>
  );
}

const Layout = styled.div`
  display: flex: ;
  flex-direction: column;
`;
