import Head from "next/head";
import styled from "styled-components";
import { useColorTheme } from "store/useColorTheme";

export default function Home() {
  const { changeColorTheme } = useColorTheme();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>테스트</Main>
      <button onClick={changeColorTheme}>test</button>
    </>
  );
}

const Main = styled.main``;
